### ISSUE TITLE
User Instances with OAI need to take the Cookies from the incoming Request

### ISSUE THREAD

**Issue by wilbersl** [SoftwareAG/cumulocity-python-api#61]
**Issue:** 
User-Instances do not work correctly with OAI-Secure, described in this [post](https://tech.forums.softwareag.com/t/c8y-microservice-python-user-session-issues/300693).

**Technical Reason:**
OAI-Secure uses a Cookie (authorization and XSRF-Token) instead of the Authorization Header from Basic Auth. When sending a request to a microservice a Authorization Header gets added, probably by the Proxy (not to sure here). This Authorization Header includes the correct TenantID, Username and the string __, which obviously won't work with the Basic Auth .build_user_instance. 

**Current Workaround**

```
from c8y_api.model.administration import CurrentUser
from c8y_api.app import MultiTenantCumulocityApp
from flask import Flask, request
import requests

rest = Flask(__name__)
c8y = MultiTenantCumulocityApp()

@rest.route('/')
def default_route():
    """Default route"""
    currentUser = CurrentUser.from_json(requests.get(c8y.bootstrap_instance.base_url + CurrentUser._resource, cookies= 
  {**request.cookies}).json())

    r = {
        "currentUser": currentUser.to_full_json()
        }
    return r, 200
```

**Proposed Solution**
Include the cookies from the incoming request into the CumulocityRestApi._create_session().

**Comment by reey** [comment]
@chisou @chsou FYI the implementation in the @c8y/client javascript library looks like this:
```
export class MicroserviceClientRequestAuth implements IAuthentication {
  // Bearer token read from cookie from header
  protected authTokenFromCookie: string | undefined;
  // Bearer/Basic auth token read from header
  protected authTokenFromHeader: string | undefined;
  protected xsrfToken: string | undefined;

  /**
   * Authenticates using the credentials which were
   * provided within the request headers of the
   * client call to the microservice.
   * @param headers
   */
  constructor(headers: IMicroserviceClientRequestHeaders = {}) {
    this.xsrfToken = this.getCookieValue(headers, 'XSRF-TOKEN');
    this.authTokenFromCookie = this.getCookieValue(headers, 'authorization');
    this.authTokenFromHeader = headers.authorization;
  }

[...]

  getFetchOptions(options: IFetchOptions): IFetchOptions {
    const headers: any = {
      Authorization: this.authTokenFromCookie
        ? `Bearer ${this.authTokenFromCookie}`
        : this.authTokenFromHeader,
      ...(this.xsrfToken ? { 'X-XSRF-TOKEN': this.xsrfToken } : undefined)
    };
    options.headers = Object.assign(headers, options.headers);
    return options;
  }

[...]
}
```

Basically if an `authorization` cookie is present, you need to ignore the `authorization` header of the incoming request.
The headers returned by `getFetchOptions` (which will then be used by the microservice in order to perform requests in the name of the user of the incoming request) will include an `authorization` header and optionally a `X-XSRF-TOKEN` header although the `X-XSRF-TOKEN` header can probably be left out as it is only required when using cookies for authorization.

The `Authorization` headers value will be ``Bearer <authTokenFromCookie>`` in case the authorization cookie was present, in case it was not present, the `Authorization` header of the incoming request is used.

**Comment by chisou** [comment]
@wilbersl, did you try something like this?

```
c8y_user = c8y.get_user_instance(request.headers, request.cookies)
```
See also this test: https://github.com/SoftwareAG/cumulocity-python-api/blob/a1139162a8bc767affc62737fc069c74a90d523b/integration_tests/test_apps.py#L57

**Comment by wilbersl** [comment]
Looks like my venv didn't update correctly. I did not see the new method signature. 

It works now, thanks!!!
